// clean up
#undef TRIXY_HAS_HELPER

#undef TRIXY_NET_TPL_DECLARATION
#undef TRIXY_NET_TPL

#undef TRIXY_SERIALIZER_TPL_DECLARATION
#undef TRIXY_SERIALIZER_TPL

#undef TRIXY_FUNCTIONAL_TPL_DECLARATION
#undef TRIXY_FUNCTIONAL_TPL

#undef TRIXY_OPTIMIZER_TPL_DECLARATION
#undef TRIXY_OPTIMIZER_TPL

#undef TRIXY_TRAINING_TPL_DECLARATION
#undef TRIXY_TRAINING_TPL

#undef TRIXY_FUNCTION_TENSOR_TPL_DECLARATION
#undef TRIXY_FUNCTION_TPL_DECLARATION

#undef TRIXY_FUNCTION_GENERIC_HELPER

#undef TRIXY_REGRESSION_TPL_DECLARATION
#undef TRIXY_REGRESSION_TPL

#undef TRIXY_BASE_CLASS_TPL_DECLARATION
#undef TRIXY_CLASS_TPL_DECLARATION
#undef TRIXY_CLASS_TPL
#undef TRIXY_CLASS_TPL_SELECT

#undef TRIXY_CHECK_TYPE_HELPER
