// clean up

#undef TRIXY_NET_TPL_DECLARATION
#undef TRIXY_NET_TPL
#undef TRIXY_NET_REQUIRE_TPL

#undef TRIXY_SERIALIZER_TPL_DECLARATION
#undef TRIXY_SERIALIZER_TPL

#undef TRIXY_FUNCTIONAL_TPL_DECLARATION
#undef TRIXY_FUNCTIONAL_TPL

#undef TRIXY_OPTIMIZER_TPL_DECLARATION
#undef TRIXY_OPTIMIZER_TPL

#undef TRIXY_TRAINING_TPL_DECLARATION
#undef TRIXY_TRAINING_TPL

#undef TRIXY_REGRESSION_TPL_DECLARATION
#undef TRIXY_REGRESSION_TPL
