// clean up

#undef TRIXY_NET_TEMPLATE
#undef TRIXY_SERIALIZER_TEMPLATE
#undef TRIXY_FUNCTIONAL_TEMPLATE
#undef TRIXY_OPTIMIZER_TEMPLATE
#undef TRIXY_TRAINING_TEMPLATE
#undef TRIXY_REGRESSION_TEMPLATE

#undef TRIXY_OPTIMIZER_TEMPLATE_CLASS
