// clean up
#undef LIQUE_TENSOR_TPL_DECLARATION
#undef LIQUE_TENSOR_TPL

#undef LIQUE_LOCKER_TPL_DECLARATION
#undef LIQUE_LOCKER_TPL

#undef LIQUE_LINEAR_TPL_DECLARATION
#undef LIQUE_LINEAR_TPL

#undef LIQUE_FUNCTION_TPL
