// clean up
#undef TRIXY_HAS_FUNCTION_HELPER
#undef TRIXY_HAS_TYPE_HELPER

#undef TRIXY_APPLY_FUNCTION_GENERIC_HELPER

#undef TRIXY_FUNCTION_GENERIC_HELPER
#undef TRIXY_FUNCTION_GENERIC_LOSS_HELPER
#undef TRIXY_FUNCTION_GENERIC_ACTIVATION_HELPER

#undef TRIXY_FUNCTION_TENSOR_TPL_DECLARATION
#undef TRIXY_FUNCTION_TPL_DECLARATION

#undef TRIXY_BASE_CLASS_TPL_DECLARATION
#undef TRIXY_CLASS_TPL_DECLARATION
#undef TRIXY_CLASS_TPL
#undef TRIXY_CLASS_TPL_SELECT

#undef TRIXY_DEF_OPT_HELPER
